👌🏻 Move to webpack
engagor/react-chat-window pull request #2
Opened 2022-07-14 08:10 UTC by matthias-deschoenmacker

## Description
In order to eliminate some critical vulnerabilities with the current tooling, we preferably move to webpack.

### Full Changelog:
🛠 Change from nwb to webpack to build the project because it has critical vulnerabilities 
📕 Replace demo with Storybook implementation
🔐 Remove deprecated dependencies gh-pages and react-highlight.js because of vulnerabilities
🗂 Restructure project: src is still the root of the project and dist is the built version

2022-07-15 11:31 UTC, thaoms approved these changes
Reviewed it and tested in storybook, but once you update this in the engagor codebase be sure to ask for a QA.

2022-07-22 12:52 UTC, jensdevlieger requested changes
I don't know much about the stories and Webpack config but looks good as far as I can see. Just a question regarding the updated React code that I'd like an answer to though 🙇

2022-07-22 12:52 UTC, jensdevlieger commented on src/components/Launcher.js
> +  componentDidUpdate(prevProps) {
Q: Will this work? The given argument changed from next props to previous props so I assume that some change in logic will be needed to make sure we can play the incoming message sound?

2022-07-25 07:47 UTC, llissssss commented
@Toinne when you have some time 🙇

2022-08-01 12:37 UTC, cedricengagor approved these changes

2022-08-01 12:37 UTC, cedricengagor commented on src/components/Launcher.js
> +  componentDidUpdate(prevProps) {
It changed because they use a different lifecycle hook. I assume that the will receive props was deprecated at some point. Meaning that it will probably happen after the component update while in the past it was the other way around. Anyhow, should still work as it did before 🆗

2022-08-09 15:40 UTC, jensdevlieger commented on src/components/Launcher.js
> +  componentDidUpdate(prevProps) {
@cedricengagor 
So since we changed it to `componentDidUpdate(prevProps)` it means that `prevProps` => old props and `this.props` => the new props right?

Looking at the following code fragment with that thought process,
```
if (isIncoming && prevProps.messageList.length > this.props.messageList.length) {
    this.playIncomingMessageSound()
}
```

It will never play a sound when a new message enters because the old props will or should never have more messages than the new props right?

2022-08-18 08:59 UTC, Toinne approved these changes

2022-08-22 09:15 UTC, matthias-deschoenmacker commented on src/components/Launcher.js
> +  componentDidUpdate(prevProps) {
Fixed, thanks. I changed the logic to take the actual props instead of prevprops and changed the direction of the `>`

2022-08-24 09:53 UTC, merged